[project]
name = "wbradycall"
version = "0.0.1"
authors = [
  { name="Brady Call", email="wbradycall@gmail.com" },
]
description = "A calculus library for Python"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/wbradycall/Calcify"